# supabase/config.toml

project_id = "farha"

[functions.generate-lyrics]
verify_jwt = false

[functions.generate-music]
verify_jwt = false

[functions.music-status]
verify_jwt = false

[functions.unlock-song]
verify_jwt = false

[functions.get-download-url]
verify_jwt = false

[functions.create-checkout]
verify_jwt = false

[functions.verify-payment]
verify_jwt = false  # ← Ajouter cette ligne

[functions.stripe-webhook]
verify_jwt = false

[functions.paypal-webhook]
verify_jwt = false

[functions.fedapay-webhook]
verify_jwt = false

[functions.send-welcome-email]
verify_jwt = false