/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,jsx}"],
  theme: {
    extend: {
      colors: {
        cream: "#FAF5EC",
        paper: "#FFFFFF",
        ink: "#14110F",
        muted: "#5C5449",
        line: "#E5DCCB",
        emerald: { DEFAULT: "#0A3832", light: "#12544B" },
        safran: { DEFAULT: "#E89528", bright: "#FAA831", bg: "#FFF8EB" },
        henne: { DEFAULT: "#B83A28", light: "#D94B37" },
      },
      fontFamily: {
        display: ["Fraunces", "serif"],
        sans: ["Inter", "sans-serif"],
        arabic: ["Amiri", "serif"],
      },
      keyframes: {
        fadeIn: { from: { opacity: "0" }, to: { opacity: "1" } },
        scaleIn: { from: { opacity: "0", transform: "scale(0.95)" }, to: { opacity: "1", transform: "scale(1)" } },
        slideUp: { from: { opacity: "0", transform: "translateY(12px)" }, to: { opacity: "1", transform: "translateY(0)" } },
        slideDown: { from: { opacity: "0", transform: "translateY(-12px)" }, to: { opacity: "1", transform: "translateY(0)" } },
        popIn: { "0%": { opacity: "0", transform: "scale(0.8)" }, "70%": { transform: "scale(1.05)" }, "100%": { opacity: "1", transform: "scale(1)" } },
        pulseGlow: { "0%, 100%": { boxShadow: "0 0 0 0 rgba(232,149,40,0.4)" }, "50%": { boxShadow: "0 0 0 12px rgba(232,149,40,0)" } },
        shimmer: { from: { backgroundPosition: "-200% 0" }, to: { backgroundPosition: "200% 0" } },
        bounceIn: { "0%": { opacity: "0", transform: "scale(0.3)" }, "50%": { transform: "scale(1.08)" }, "70%": { transform: "scale(0.95)" }, "100%": { opacity: "1", transform: "scale(1)" } },
        noteFloat: { "0%": { opacity: "1", transform: "translateY(0) rotate(0deg)" }, "100%": { opacity: "0", transform: "translateY(-40px) rotate(15deg)" } },
        micPulse: { "0%, 100%": { transform: "scale(1)" }, "50%": { transform: "scale(1.15)" } },
        successCheck: { "0%": { strokeDashoffset: "50" }, "100%": { strokeDashoffset: "0" } },
        confettiBurst: { "0%": { opacity: "1", transform: "translateY(0) scale(1)" }, "100%": { opacity: "0", transform: "translateY(-60px) scale(0.5)" } },
      },
      animation: {
        fadeIn: "fadeIn 0.2s ease-out",
        scaleIn: "scaleIn 0.2s ease-out",
        slideUp: "slideUp 0.35s ease-out",
        slideDown: "slideDown 0.35s ease-out",
        popIn: "popIn 0.4s cubic-bezier(0.34, 1.56, 0.64, 1)",
        pulseGlow: "pulseGlow 2s ease-in-out infinite",
        shimmer: "shimmer 2s linear infinite",
        bounceIn: "bounceIn 0.5s cubic-bezier(0.34, 1.56, 0.64, 1)",
        noteFloat: "noteFloat 1.2s ease-out forwards",
        micPulse: "micPulse 1s ease-in-out infinite",
        successCheck: "successCheck 0.6s ease-out forwards",
        confettiBurst: "confettiBurst 0.8s ease-out forwards",
      },
    },
  },
  plugins: [],
};
